from enum import Enum


class EdgeLayer(str, Enum):

    STRUCTURAL = "STRUCTURAL"

    SEMANTIC_RESOLVED = "SEMANTIC_RESOLVED"

    INHERITANCE_DEFERRED = "INHERITANCE_DEFERRED"

    RUNTIME_APPROXIMATION = "RUNTIME_APPROXIMATION"

    SPECULATIVE = "SPECULATIVE"

    FRAMEWORK = "FRAMEWORK"

    EXTERNAL = "EXTERNAL"
