from enum import Enum


class ProvenanceType(str, Enum):

    AST_DIRECT = "AST_DIRECT"

    SYMBOL_INDEX = "SYMBOL_INDEX"

    INHERITANCE_TRAVERSAL = "INHERITANCE_TRAVERSAL"

    FRAMEWORK_HEURISTIC = "FRAMEWORK_HEURISTIC"

    LOCAL_MODULE = "LOCAL_MODULE"

    IMPORT_ANALYSIS = "IMPORT_ANALYSIS"

    DYNAMIC_DISPATCH = "DYNAMIC_DISPATCH"

    IMPORT_RESOLUTION = "IMPORT_RESOLUTION"
