from enum import Enum


class ResolverStage(str, Enum):

    AST_PASS = "AST_PASS"

    RELATIONSHIP_EXTRACTION_PASS = "RELATIONSHIP_EXTRACTION_PASS"

    SEMANTIC_PASS = "SEMANTIC_PASS"

    INHERITANCE_PASS = "INHERITANCE_PASS"

    FRAMEWORK_PASS = "FRAMEWORK_PASS"

    POST_PROCESS_PASS = "POST_PROCESS_PASS"
